// Every emoji the picker offers, and the name you can type for it.
//
// GENERATED from Python's unicodedata -- see the note in the picker. Hand
// writing this means hand writing a thousand names, and the names are what
// search looks at, so they would be the first thing to rot.
//
// Only the pictographic planes are included (U+1F300-1F5FF, 1F600-1F64F,
// 1F680-1F6FF, 1F900-1F9FF, 1FA70-1FAFF) plus a hand-picked set of older
// symbols. Everything in those blocks is emoji-presentation by default, so
// the grid cannot fill up with monochrome dingbats and tofu. The older ones
// each carry U+FE0F for the same reason.
//
// Sections are assigned by keyword against the Unicode name. That is an
// approximation and some things land oddly; search is the real way in, and
// it matches on the name, which is exact.

export const EMOJI_SECTIONS = [
  {
    id: 'smileys',
    label: 'Smileys & people',
    items: [
      ['🌆', 'cityscape_at_dusk'], ['🌍', 'earth_globe_europe_africa'], ['🌎', 'earth_globe_americas'], ['🌏', 'earth_globe_asia_australia'],
      ['🌚', 'new_moon_with_face'], ['🌛', 'first_quarter_moon_with_face'], ['🌜', 'last_quarter_moon_with_face'], ['🌝', 'full_moon_with_face'],
      ['🌞', 'sun_with_face'], ['🌬', 'wind_blowing_face'], ['🌴', 'palm_tree'], ['🌽', 'ear_of_maize'],
      ['🌾', 'ear_of_rice'], ['🍃', 'leaf_fluttering_in_wind'], ['🍐', 'pear'], ['🍖', 'meat_on_bone'],
      ['🍗', 'poultry_leg'], ['🍵', 'teacup_without_handle'], ['🍼', 'baby_bottle'], ['🎓', 'graduation_cap'],
      ['🎔', 'heart_with_tip_on_the_left'], ['🎩', 'top_hat'], ['🎬', 'clapper_board'], ['🎽', 'running_shirt_with_sash'],
      ['🎿', 'ski_and_ski_boot'], ['🏈', 'american_football'], ['🏉', 'rugby_football'], ['🏔', 'snow_capped_mountain'],
      ['🏙', 'cityscape'], ['🐌', 'snail'], ['🐒', 'monkey'], ['🐣', 'hatching_chick'],
      ['🐤', 'baby_chick'], ['🐥', 'front_facing_baby_chick'], ['🐭', 'mouse_face'], ['🐮', 'cow_face'],
      ['🐯', 'tiger_face'], ['🐰', 'rabbit_face'], ['🐱', 'cat_face'], ['🐲', 'dragon_face'],
      ['🐳', 'spouting_whale'], ['🐴', 'horse_face'], ['🐵', 'monkey_face'], ['🐶', 'dog_face'],
      ['🐷', 'pig_face'], ['🐸', 'frog_face'], ['🐹', 'hamster_face'], ['🐺', 'wolf_face'],
      ['🐻', 'bear_face'], ['🐼', 'panda_face'], ['🐽', 'pig_nose'], ['👀', 'eyes'],
      ['👁', 'eye'], ['👂', 'ear'], ['👃', 'nose'], ['👄', 'mouth'],
      ['👅', 'tongue'], ['👆', 'white_up_pointing_backhand_index'], ['👇', 'white_down_pointing_backhand_index'], ['👈', 'white_left_pointing_backhand_index'],
      ['👉', 'white_right_pointing_backhand_index'], ['👊', 'fisted_hand_sign'], ['👋', 'waving_hand_sign'], ['👌', 'ok_hand_sign'],
      ['👍', 'thumbs_up_sign'], ['👎', 'thumbs_down_sign'], ['👏', 'clapping_hands_sign'], ['👐', 'open_hands_sign'],
      ['👑', 'crown'], ['👒', 'womans_hat'], ['👓', 'eyeglasses'], ['👕', 't_shirt'],
      ['👖', 'jeans'], ['👗', 'dress'], ['👘', 'kimono'], ['👙', 'bikini'],
      ['👚', 'womans_clothes'], ['👛', 'purse'], ['👜', 'handbag'], ['👞', 'mans_shoe'],
      ['👟', 'athletic_shoe'], ['👠', 'high_heeled_shoe'], ['👡', 'womans_sandal'], ['👢', 'womans_boots'],
      ['👣', 'footprints'], ['👤', 'bust_in_silhouette'], ['👥', 'busts_in_silhouette'], ['👦', 'boy'],
      ['👧', 'girl'], ['👨', 'man'], ['👩', 'woman'], ['👪', 'family'],
      ['👫', 'man_and_woman_holding_hands'], ['👬', 'two_men_holding_hands'], ['👭', 'two_women_holding_hands'], ['👮', 'police_officer'],
      ['👯', 'woman_with_bunny_ears'], ['👱', 'person_with_blond_hair'], ['👲', 'man_with_gua_pi_mao'], ['👳', 'man_with_turban'],
      ['👴', 'older_man'], ['👵', 'older_woman'], ['👶', 'baby'], ['👷', 'construction_worker'],
      ['👸', 'princess'], ['👹', 'japanese_ogre'], ['👺', 'japanese_goblin'], ['👻', 'ghost'],
      ['👼', 'baby_angel'], ['👽', 'extraterrestrial_alien'], ['👾', 'alien_monster'], ['💀', 'skull'],
      ['💁', 'information_desk_person'], ['💂', 'guardsman'], ['💃', 'dancer'], ['💄', 'lipstick'],
      ['💅', 'nail_polish'], ['💆', 'face_massage'], ['💇', 'haircut'], ['💉', 'syringe'],
      ['💋', 'kiss_mark'], ['💍', 'ring'], ['💏', 'kiss'], ['💑', 'couple_with_heart'],
      ['💓', 'beating_heart'], ['💔', 'broken_heart'], ['💕', 'two_hearts'], ['💖', 'sparkling_heart'],
      ['💗', 'growing_heart'], ['💘', 'heart_with_arrow'], ['💙', 'blue_heart'], ['💚', 'green_heart'],
      ['💛', 'yellow_heart'], ['💜', 'purple_heart'], ['💝', 'heart_with_ribbon'], ['💞', 'revolving_hearts'],
      ['💟', 'heart_decoration'], ['💤', 'sleeping_symbol'], ['💩', 'pile_of_poo'], ['💬', 'speech_balloon'],
      ['💭', 'thought_balloon'], ['💻', 'personal_computer'], ['📁', 'file_folder'], ['📂', 'open_file_folder'],
      ['📆', 'tear_off_calendar'], ['📢', 'public_address_loudspeaker'], ['📣', 'cheering_megaphone'], ['📿', 'prayer_beads'],
      ['🔟', 'keycap_ten'], ['🔠', 'input_symbol_for_latin_capital_letters'], ['🔮', 'crystal_ball'], ['🕐', 'clock_face_one_oclock'],
      ['🕑', 'clock_face_two_oclock'], ['🕒', 'clock_face_three_oclock'], ['🕓', 'clock_face_four_oclock'], ['🕔', 'clock_face_five_oclock'],
      ['🕕', 'clock_face_six_oclock'], ['🕖', 'clock_face_seven_oclock'], ['🕗', 'clock_face_eight_oclock'], ['🕘', 'clock_face_nine_oclock'],
      ['🕙', 'clock_face_ten_oclock'], ['🕚', 'clock_face_eleven_oclock'], ['🕛', 'clock_face_twelve_oclock'], ['🕜', 'clock_face_one_thirty'],
      ['🕝', 'clock_face_two_thirty'], ['🕞', 'clock_face_three_thirty'], ['🕟', 'clock_face_four_thirty'], ['🕠', 'clock_face_five_thirty'],
      ['🕡', 'clock_face_six_thirty'], ['🕢', 'clock_face_seven_thirty'], ['🕣', 'clock_face_eight_thirty'], ['🕤', 'clock_face_nine_thirty'],
      ['🕥', 'clock_face_ten_thirty'], ['🕦', 'clock_face_eleven_thirty'], ['🕧', 'clock_face_twelve_thirty'], ['🕭', 'ringing_bell'],
      ['🕰', 'mantelpiece_clock'], ['🕱', 'black_skull_and_crossbones'], ['🕳', 'hole'], ['🕴', 'man_in_business_suit_levitating'],
      ['🕶', 'dark_sunglasses'], ['🕺', 'man_dancing'], ['🕻', 'left_hand_telephone_receiver'], ['🕽', 'right_hand_telephone_receiver'],
      ['🖇', 'linked_paperclips'], ['🖎', 'left_writing_hand'], ['🖏', 'turned_ok_hand_sign'], ['🖐', 'raised_hand_with_fingers_splayed'],
      ['🖑', 'reversed_raised_hand_with_fingers_splayed'], ['🖒', 'reversed_thumbs_up_sign'], ['🖓', 'reversed_thumbs_down_sign'], ['🖔', 'reversed_victory_hand'],
      ['🖕', 'reversed_hand_with_middle_finger_extended'], ['🖖', 'raised_hand_with_part_between_middle_and_ring_fingers'], ['🖗', 'white_down_pointing_left_hand_index'], ['🖜', 'black_left_pointing_backhand_index'],
      ['🖝', 'black_right_pointing_backhand_index'], ['🖢', 'black_up_pointing_backhand_index'], ['🖣', 'black_down_pointing_backhand_index'], ['🖤', 'black_heart'],
      ['🖳', 'old_personal_computer'], ['🖿', 'black_folder'], ['🗀', 'folder'], ['🗁', 'open_folder'],
      ['🗢', 'lips'], ['🗣', 'speaking_head_in_silhouette'], ['🗨', 'left_speech_bubble'], ['🗩', 'right_speech_bubble'],
      ['🗪', 'two_speech_bubbles'], ['🗫', 'three_speech_bubbles'], ['😀', 'grinning_face'], ['😁', 'grinning_face_with_smiling_eyes'],
      ['😂', 'face_with_tears_of_joy'], ['😃', 'smiling_face_with_open_mouth'], ['😄', 'smiling_face_with_open_mouth_and_smiling_eyes'], ['😅', 'smiling_face_with_open_mouth_and_cold_sweat'],
      ['😆', 'smiling_face_with_open_mouth_and_tightly_closed_eyes'], ['😇', 'smiling_face_with_halo'], ['😈', 'smiling_face_with_horns'], ['😉', 'winking_face'],
      ['😊', 'smiling_face_with_smiling_eyes'], ['😋', 'face_savouring_delicious_food'], ['😌', 'relieved_face'], ['😍', 'smiling_face_with_heart_shaped_eyes'],
      ['😎', 'smiling_face_with_sunglasses'], ['😏', 'smirking_face'], ['😐', 'neutral_face'], ['😑', 'expressionless_face'],
      ['😒', 'unamused_face'], ['😓', 'face_with_cold_sweat'], ['😔', 'pensive_face'], ['😕', 'confused_face'],
      ['😖', 'confounded_face'], ['😗', 'kissing_face'], ['😘', 'face_throwing_a_kiss'], ['😙', 'kissing_face_with_smiling_eyes'],
      ['😚', 'kissing_face_with_closed_eyes'], ['😛', 'face_with_stuck_out_tongue'], ['😜', 'face_with_stuck_out_tongue_and_winking_eye'], ['😝', 'face_with_stuck_out_tongue_and_tightly_closed_eyes'],
      ['😞', 'disappointed_face'], ['😟', 'worried_face'], ['😠', 'angry_face'], ['😡', 'pouting_face'],
      ['😢', 'crying_face'], ['😣', 'persevering_face'], ['😤', 'face_with_look_of_triumph'], ['😥', 'disappointed_but_relieved_face'],
      ['😦', 'frowning_face_with_open_mouth'], ['😧', 'anguished_face'], ['😨', 'fearful_face'], ['😩', 'weary_face'],
      ['😪', 'sleepy_face'], ['😫', 'tired_face'], ['😬', 'grimacing_face'], ['😭', 'loudly_crying_face'],
      ['😮', 'face_with_open_mouth'], ['😯', 'hushed_face'], ['😰', 'face_with_open_mouth_and_cold_sweat'], ['😱', 'face_screaming_in_fear'],
      ['😲', 'astonished_face'], ['😳', 'flushed_face'], ['😴', 'sleeping_face'], ['😵', 'dizzy_face'],
      ['😶', 'face_without_mouth'], ['😷', 'face_with_medical_mask'], ['😸', 'grinning_cat_face_with_smiling_eyes'], ['😹', 'cat_face_with_tears_of_joy'],
      ['😺', 'smiling_cat_face_with_open_mouth'], ['😻', 'smiling_cat_face_with_heart_shaped_eyes'], ['😼', 'cat_face_with_wry_smile'], ['😽', 'kissing_cat_face_with_closed_eyes'],
      ['😾', 'pouting_cat_face'], ['😿', 'crying_cat_face'], ['🙀', 'weary_cat_face'], ['🙁', 'slightly_frowning_face'],
      ['🙂', 'slightly_smiling_face'], ['🙃', 'upside_down_face'], ['🙄', 'face_with_rolling_eyes'], ['🙅', 'face_with_no_good_gesture'],
      ['🙆', 'face_with_ok_gesture'], ['🙇', 'person_bowing_deeply'], ['🙈', 'see_no_evil_monkey'], ['🙉', 'hear_no_evil_monkey'],
      ['🙊', 'speak_no_evil_monkey'], ['🙋', 'happy_person_raising_one_hand'], ['🙌', 'person_raising_both_hands_in_celebration'], ['🙍', 'person_frowning'],
      ['🙎', 'person_with_pouting_face'], ['🙏', 'person_with_folded_hands'], ['🚅', 'high_speed_train_with_bullet_nose'], ['🚓', 'police_car'],
      ['🚔', 'oncoming_police_car'], ['🚨', 'police_cars_revolving_light'], ['🚼', 'baby_symbol'], ['🛉', 'boys_symbol'],
      ['🛊', 'girls_symbol'], ['🛌', 'sleeping_accommodation'], ['🛟', 'ring_buoy'], ['🤌', 'pinched_fingers'],
      ['🤍', 'white_heart'], ['🤎', 'brown_heart'], ['🤏', 'pinching_hand'], ['🤐', 'zipper_mouth_face'],
      ['🤑', 'money_mouth_face'], ['🤒', 'face_with_thermometer'], ['🤓', 'nerd_face'], ['🤔', 'thinking_face'],
      ['🤕', 'face_with_head_bandage'], ['🤖', 'robot_face'], ['🤗', 'hugging_face'], ['🤙', 'call_me_hand'],
      ['🤚', 'raised_back_of_hand'], ['🤛', 'left_facing_fist'], ['🤜', 'right_facing_fist'], ['🤝', 'handshake'],
      ['🤞', 'hand_with_index_and_middle_fingers_crossed'], ['🤟', 'i_love_you_hand_sign'], ['🤠', 'face_with_cowboy_hat'], ['🤡', 'clown_face'],
      ['🤢', 'nauseated_face'], ['🤤', 'drooling_face'], ['🤥', 'lying_face'], ['🤦', 'face_palm'],
      ['🤧', 'sneezing_face'], ['🤨', 'face_with_one_eyebrow_raised'], ['🤩', 'grinning_face_with_star_eyes'], ['🤪', 'grinning_face_with_one_large_and_one_small_eye'],
      ['🤫', 'face_with_finger_covering_closed_lips'], ['🤬', 'serious_face_with_symbols_covering_mouth'], ['🤭', 'smiling_face_with_smiling_eyes_and_hand_covering_mouth'], ['🤮', 'face_with_open_mouth_vomiting'],
      ['🤯', 'shocked_face_with_exploding_head'], ['🤰', 'pregnant_woman'], ['🤲', 'palms_up_together'], ['🤳', 'selfie'],
      ['🤴', 'prince'], ['🤵', 'man_in_tuxedo'], ['🤸', 'person_doing_cartwheel'], ['🤾', 'handball'],
      ['🥂', 'clinking_glasses'], ['🥊', 'boxing_glove'], ['🥭', 'mango'], ['🥰', 'smiling_face_with_smiling_eyes_and_three_hearts'],
      ['🥱', 'yawning_face'], ['🥲', 'smiling_face_with_tear'], ['🥳', 'face_with_party_horn_and_party_hat'], ['🥴', 'face_with_uneven_eyes_and_wavy_mouth'],
      ['🥵', 'overheated_face'], ['🥶', 'freezing_face'], ['🥷', 'ninja'], ['🥸', 'disguised_face'],
      ['🥹', 'face_holding_back_tears'], ['🥺', 'face_with_pleading_eyes'], ['🥻', 'sari'], ['🥼', 'lab_coat'],
      ['🥾', 'hiking_boot'], ['🥿', 'flat_shoe'], ['🦁', 'lion_face'], ['🦄', 'unicorn_face'],
      ['🦊', 'fox_face'], ['🦒', 'giraffe_face'], ['🦓', 'zebra_face'], ['🦰', 'emoji_component_red_hair'],
      ['🦱', 'emoji_component_curly_hair'], ['🦳', 'emoji_component_white_hair'], ['🦴', 'bone'], ['🦵', 'leg'],
      ['🦶', 'foot'], ['🦷', 'tooth'], ['🦸', 'superhero'], ['🦹', 'supervillain'],
      ['🦻', 'ear_with_hearing_aid'], ['🦼', 'motorized_wheelchair'], ['🦽', 'manual_wheelchair'], ['🦾', 'mechanical_arm'],
      ['🦿', 'mechanical_leg'], ['🧍', 'standing_person'], ['🧎', 'kneeling_person'], ['🧏', 'deaf_person'],
      ['🧐', 'face_with_monocle'], ['🧑', 'adult'], ['🧓', 'older_adult'], ['🧔', 'bearded_person'],
      ['🧕', 'person_with_headscarf'], ['🧖', 'person_in_steamy_room'], ['🧗', 'person_climbing'], ['🧘', 'person_in_lotus_position'],
      ['🧙', 'mage'], ['🧚', 'fairy'], ['🧛', 'vampire'], ['🧜', 'merperson'],
      ['🧝', 'elf'], ['🧞', 'genie'], ['🧟', 'zombie'], ['🧠', 'brain'],
      ['🧡', 'orange_heart'], ['🧢', 'billed_cap'], ['🧣', 'scarf'], ['🧤', 'gloves'],
      ['🧥', 'coat'], ['🧦', 'socks'], ['🧸', 'teddy_bear'], ['🩰', 'ballet_shoes'],
      ['🩴', 'thong_sandal'], ['🩵', 'light_blue_heart'], ['🩶', 'grey_heart'], ['🩷', 'pink_heart'],
      ['🪐', 'ringed_planet'], ['🪑', 'chair'], ['🪠', 'plunger'], ['🪥', 'toothbrush'],
      ['🪭', 'folding_hand_fan'], ['🪮', 'hair_pick'], ['🪯', 'khanda'], ['🫀', 'anatomical_heart'],
      ['🫁', 'lungs'], ['🫂', 'people_hugging'], ['🫃', 'pregnant_man'], ['🫄', 'pregnant_person'],
      ['🫅', 'person_with_crown'], ['🫆', 'fingerprint'], ['🫗', 'pouring_liquid'], ['🫠', 'melting_face'],
      ['🫡', 'saluting_face'], ['🫢', 'face_with_open_eyes_and_hand_over_mouth'], ['🫣', 'face_with_peeking_eye'], ['🫤', 'face_with_diagonal_mouth'],
      ['🫥', 'dotted_line_face'], ['🫨', 'shaking_face'], ['🫩', 'face_with_bags_under_eyes'], ['🫰', 'hand_with_index_finger_and_thumb_crossed'],
      ['🫱', 'rightwards_hand'], ['🫲', 'leftwards_hand'], ['🫳', 'palm_down_hand'], ['🫴', 'palm_up_hand'],
      ['🫶', 'heart_hands'], ['🫷', 'leftwards_pushing_hand'], ['🫸', 'rightwards_pushing_hand'], ['❤️', 'red_heart'],
      ['⛄', 'snowman'], ['⏰', 'alarm_clock'], ['♥️', 'hearts'], ['☸️', 'wheel_of_dharma'],
      ['⛳', 'golf_flag'], ['⛹️', 'bouncing_ball'],
    ],
  },
  {
    id: 'food',
    label: 'Food & drink',
    items: [
      ['🌋', 'volcano'], ['🌌', 'milky_way'], ['🌭', 'hot_dog'], ['🌮', 'taco'],
      ['🌯', 'burrito'], ['🌶', 'hot_pepper'], ['🌸', 'cherry_blossom'], ['🍅', 'tomato'],
      ['🍇', 'grapes'], ['🍈', 'melon'], ['🍉', 'watermelon'], ['🍊', 'tangerine'],
      ['🍋', 'lemon'], ['🍌', 'banana'], ['🍍', 'pineapple'], ['🍎', 'red_apple'],
      ['🍏', 'green_apple'], ['🍑', 'peach'], ['🍒', 'cherries'], ['🍓', 'strawberry'],
      ['🍔', 'hamburger'], ['🍕', 'slice_of_pizza'], ['🍘', 'rice_cracker'], ['🍙', 'rice_ball'],
      ['🍚', 'cooked_rice'], ['🍛', 'curry_and_rice'], ['🍜', 'steaming_bowl'], ['🍞', 'bread'],
      ['🍟', 'french_fries'], ['🍠', 'roasted_sweet_potato'], ['🍣', 'sushi'], ['🍤', 'fried_shrimp'],
      ['🍥', 'fish_cake_with_swirl_design'], ['🍦', 'soft_ice_cream'], ['🍧', 'shaved_ice'], ['🍨', 'ice_cream'],
      ['🍩', 'doughnut'], ['🍪', 'cookie'], ['🍫', 'chocolate_bar'], ['🍬', 'candy'],
      ['🍭', 'lollipop'], ['🍮', 'custard'], ['🍯', 'honey_pot'], ['🍰', 'shortcake'],
      ['🍱', 'bento_box'], ['🍲', 'pot_of_food'], ['🍴', 'fork_and_knife'], ['🍶', 'sake_bottle_and_cup'],
      ['🍷', 'wine_glass'], ['🍸', 'cocktail_glass'], ['🍺', 'beer_mug'], ['🍻', 'clinking_beer_mugs'],
      ['🍽', 'fork_and_knife_with_plate'], ['🍾', 'bottle_with_popping_cork'], ['🍿', 'popcorn'], ['🎂', 'birthday_cake'],
      ['🎳', 'bowling'], ['🏧', 'automated_teller_machine'], ['🐝', 'honeybee'], ['🔇', 'speaker_with_cancellation_stroke'],
      ['🔕', 'bell_with_cancellation_stroke'], ['🕏', 'bowl_of_hygieia'], ['🕯', 'candle'], ['🗙', 'cancellation_x'],
      ['🗡', 'dagger_knife'], ['🛆', 'triangle_with_rounded_corners'], ['🛶', 'canoe'], ['🥃', 'tumbler_glass'],
      ['🥄', 'spoon'], ['🥐', 'croissant'], ['🥑', 'avocado'], ['🥒', 'cucumber'],
      ['🥓', 'bacon'], ['🥔', 'potato'], ['🥕', 'carrot'], ['🥖', 'baguette_bread'],
      ['🥗', 'green_salad'], ['🥘', 'shallow_pan_of_food'], ['🥙', 'stuffed_flatbread'], ['🥚', 'egg'],
      ['🥛', 'glass_of_milk'], ['🥜', 'peanuts'], ['🥝', 'kiwifruit'], ['🥞', 'pancakes'],
      ['🥟', 'dumpling'], ['🥠', 'fortune_cookie'], ['🥢', 'chopsticks'], ['🥣', 'bowl_with_spoon'],
      ['🥤', 'cup_with_straw'], ['🥥', 'coconut'], ['🥦', 'broccoli'], ['🥧', 'pie'],
      ['🥨', 'pretzel'], ['🥩', 'cut_of_meat'], ['🥪', 'sandwich'], ['🥫', 'canned_food'],
      ['🥮', 'moon_cake'], ['🥯', 'bagel'], ['🦀', 'crab'], ['🦋', 'butterfly'],
      ['🦐', 'shrimp'], ['🦞', 'lobster'], ['🦪', 'oyster'], ['🦯', 'probing_cane'],
      ['🧀', 'cheese_wedge'], ['🧁', 'cupcake'], ['🧂', 'salt_shaker'], ['🧄', 'garlic'],
      ['🧅', 'onion'], ['🧆', 'falafel'], ['🧇', 'waffle'], ['🧈', 'butter'],
      ['🧉', 'mate_drink'], ['🧋', 'bubble_tea'], ['🧩', 'jigsaw_puzzle_piece'], ['🧴', 'lotion_bottle'],
      ['🩱', 'one_piece_swimsuit'], ['🪺', 'nest_with_eggs'], ['🫑', 'bell_pepper'], ['🫓', 'flatbread'],
      ['🫔', 'tamale'], ['🫕', 'fondue'], ['🫖', 'teapot'], ['🫘', 'beans'],
      ['🫙', 'jar'], ['🫜', 'root_vegetable'],
    ],
  },
  {
    id: 'nature',
    label: 'Animals & nature',
    items: [
      ['🌁', 'foggy'], ['🌃', 'night_with_stars'], ['🌄', 'sunrise_over_mountains'], ['🌅', 'sunrise'],
      ['🌇', 'sunset_over_buildings'], ['🌈', 'rainbow'], ['🌊', 'water_wave'], ['🌐', 'globe_with_meridians'],
      ['🌑', 'new_moon_symbol'], ['🌒', 'waxing_crescent_moon_symbol'], ['🌓', 'first_quarter_moon_symbol'], ['🌔', 'waxing_gibbous_moon_symbol'],
      ['🌕', 'full_moon_symbol'], ['🌖', 'waning_gibbous_moon_symbol'], ['🌗', 'last_quarter_moon_symbol'], ['🌘', 'waning_crescent_moon_symbol'],
      ['🌙', 'crescent_moon'], ['🌟', 'glowing_star'], ['🌠', 'shooting_star'], ['🌢', 'black_droplet'],
      ['🌣', 'white_sun'], ['🌤', 'white_sun_with_small_cloud'], ['🌥', 'white_sun_behind_cloud'], ['🌦', 'white_sun_behind_cloud_with_rain'],
      ['🌧', 'cloud_with_rain'], ['🌨', 'cloud_with_snow'], ['🌩', 'cloud_with_lightning'], ['🌪', 'cloud_with_tornado'],
      ['🌫', 'fog'], ['🌰', 'chestnut'], ['🌱', 'seedling'], ['🌲', 'evergreen_tree'],
      ['🌳', 'deciduous_tree'], ['🌵', 'cactus'], ['🌷', 'tulip'], ['🌹', 'rose'],
      ['🌻', 'sunflower'], ['🌼', 'blossom'], ['🌿', 'herb'], ['🍀', 'four_leaf_clover'],
      ['🍁', 'maple_leaf'], ['🍂', 'fallen_leaf'], ['🍄', 'mushroom'], ['🎃', 'jack_o_lantern'],
      ['🎄', 'christmas_tree'], ['🎆', 'fireworks'], ['🎇', 'firework_sparkler'], ['🎋', 'tanabata_tree'],
      ['🎐', 'wind_chime'], ['🎑', 'moon_viewing_ceremony'], ['🎕', 'bouquet_of_flowers'], ['🎘', 'musical_keyboard_with_jacks'],
      ['🎞', 'film_frames'], ['🎠', 'carousel_horse'], ['🎣', 'fishing_pole_and_fish'], ['🎴', 'flower_playing_cards'],
      ['🎹', 'musical_keyboard'], ['🏂', 'snowboarder'], ['🏇', 'horse_racing'], ['🏏', 'cricket_bat_and_ball'],
      ['🏮', 'izakaya_lantern'], ['🏱', 'white_pennant'], ['🏲', 'black_pennant'], ['🏵', 'rosette'],
      ['🏶', 'black_rosette'], ['🐁', 'mouse'], ['🐂', 'ox'], ['🐃', 'water_buffalo'],
      ['🐄', 'cow'], ['🐅', 'tiger'], ['🐆', 'leopard'], ['🐇', 'rabbit'],
      ['🐈', 'cat'], ['🐉', 'dragon'], ['🐊', 'crocodile'], ['🐋', 'whale'],
      ['🐍', 'snake'], ['🐎', 'horse'], ['🐏', 'ram'], ['🐐', 'goat'],
      ['🐑', 'sheep'], ['🐔', 'chicken'], ['🐕', 'dog'], ['🐖', 'pig'],
      ['🐗', 'boar'], ['🐘', 'elephant'], ['🐙', 'octopus'], ['🐚', 'spiral_shell'],
      ['🐛', 'bug'], ['🐜', 'ant'], ['🐞', 'lady_beetle'], ['🐟', 'fish'],
      ['🐠', 'tropical_fish'], ['🐡', 'blowfish'], ['🐢', 'turtle'], ['🐦', 'bird'],
      ['🐧', 'penguin'], ['🐨', 'koala'], ['🐩', 'poodle'], ['🐪', 'dromedary_camel'],
      ['🐫', 'bactrian_camel'], ['🐬', 'dolphin'], ['🐾', 'paw_prints'], ['💐', 'bouquet'],
      ['💧', 'droplet'], ['💮', 'white_flower'], ['💸', 'money_with_wings'], ['📋', 'clipboard'],
      ['📡', 'satellite_antenna'], ['📤', 'outbox_tray'], ['📥', 'inbox_tray'], ['📪', 'closed_mailbox_with_lowered_flag'],
      ['📫', 'closed_mailbox_with_raised_flag'], ['📬', 'open_mailbox_with_raised_flag'], ['📭', 'open_mailbox_with_lowered_flag'], ['📮', 'postbox'],
      ['📶', 'antenna_with_bars'], ['🔄', 'anticlockwise_downwards_and_upwards_open_circle_arrows'], ['🔉', 'speaker_with_one_sound_wave'], ['🔊', 'speaker_with_three_sound_waves'],
      ['🔋', 'battery'], ['🔥', 'fire'], ['🔯', 'six_pointed_star_with_middle_dot'], ['🕩', 'right_speaker_with_one_sound_wave'],
      ['🕪', 'right_speaker_with_three_sound_waves'], ['🕬', 'bullhorn_with_sound_waves'], ['🕷', 'spider'], ['🕸', 'spider_web'],
      ['🖁', 'clamshell_mobile_phone'], ['🖅', 'flying_envelope'], ['🖦', 'keyboard_and_mouse'], ['🖪', 'black_hard_shell_floppy_disk'],
      ['🖫', 'white_hard_shell_floppy_disk'], ['🖬', 'soft_shell_floppy_disk'], ['🖮', 'wired_keyboard'], ['🖯', 'one_button_mouse'],
      ['🖰', 'two_button_mouse'], ['🖱', 'three_button_mouse'], ['🖼', 'frame_with_picture'], ['🖽', 'frame_with_tiles'],
      ['🖾', 'frame_with_an_x'], ['🗃', 'card_file_box'], ['🗔', 'desktop_window'], ['🗳', 'ballot_box_with_ballot'],
      ['🗵', 'ballot_box_with_script_x'], ['🗷', 'ballot_box_with_bold_script_x'], ['🗹', 'ballot_box_with_bold_check'], ['🚄', 'high_speed_train'],
      ['🚆', 'train'], ['🚊', 'tram'], ['🚋', 'tram_car'], ['🚒', 'fire_engine'],
      ['🚡', 'aerial_tramway'], ['🚰', 'potable_water_symbol'], ['🚱', 'non_potable_water_symbol'], ['🚾', 'water_closet'],
      ['🛀', 'bath'], ['🛁', 'bathtub'], ['🛱', 'oncoming_fire_engine'], ['🛸', 'flying_saucer'],
      ['🛹', 'skateboard'], ['🤽', 'water_polo'], ['🥀', 'wilted_flower'], ['🥏', 'flying_disc'],
      ['🥡', 'takeout_box'], ['🥬', 'leafy_green'], ['🦂', 'scorpion'], ['🦅', 'eagle'],
      ['🦆', 'duck'], ['🦇', 'bat'], ['🦈', 'shark'], ['🦉', 'owl'],
      ['🦌', 'deer'], ['🦍', 'gorilla'], ['🦎', 'lizard'], ['🦏', 'rhinoceros'],
      ['🦑', 'squid'], ['🦕', 'sauropod'], ['🦗', 'cricket'], ['🦚', 'peacock'],
      ['🦛', 'hippopotamus'], ['🦜', 'parrot'], ['🦟', 'mosquito'], ['🦠', 'microbe'],
      ['🦡', 'badger'], ['🦢', 'swan'], ['🦣', 'mammoth'], ['🦤', 'dodo'],
      ['🦥', 'sloth'], ['🦦', 'otter'], ['🦧', 'orangutan'], ['🦨', 'skunk'],
      ['🦩', 'flamingo'], ['🦫', 'beaver'], ['🦭', 'seal'], ['🦮', 'guide_dog'],
      ['🧃', 'beverage_box'], ['🧨', 'firecracker'], ['🧯', 'fire_extinguisher'], ['🧰', 'toolbox'],
      ['🪆', 'nesting_dolls'], ['🪟', 'window'], ['🪡', 'sewing_needle'], ['🪤', 'mouse_trap'],
      ['🪪', 'identification_card'], ['🪫', 'low_battery'], ['🪰', 'fly'], ['🪱', 'worm'],
      ['🪲', 'beetle'], ['🪳', 'cockroach'], ['🪴', 'potted_plant'], ['🪶', 'feather'],
      ['🪷', 'lotus'], ['🪸', 'coral'], ['🪹', 'empty_nest'], ['🪼', 'jellyfish'],
      ['🪽', 'wing'], ['🪾', 'leafless_tree'], ['⭐', 'star'], ['☀️', 'sun'],
      ['☁️', 'cloud'], ['☔', 'umbrella_with_rain'], ['⏳', 'hourglass_flowing'], ['☑️', 'ballot_box_with_check'],
      ['❄️', 'snowflake'], ['✴️', 'eight_pointed_star'],
    ],
  },
  {
    id: 'activity',
    label: 'Activities',
    items: [
      ['🎀', 'ribbon'], ['🎈', 'balloon'], ['🎉', 'party_popper'], ['🎊', 'confetti_ball'],
      ['🎖', 'military_medal'], ['🎗', 'reminder_ribbon'], ['🎙', 'studio_microphone'], ['🎜', 'beamed_ascending_musical_notes'],
      ['🎝', 'beamed_descending_musical_notes'], ['🎟', 'admission_tickets'], ['🎤', 'microphone'], ['🎧', 'headphone'],
      ['🎨', 'artist_palette'], ['🎪', 'circus_tent'], ['🎫', 'ticket'], ['🎭', 'performing_arts'],
      ['🎮', 'video_game'], ['🎲', 'game_die'], ['🎵', 'musical_note'], ['🎶', 'multiple_musical_notes'],
      ['🎷', 'saxophone'], ['🎸', 'guitar'], ['🎺', 'trumpet'], ['🎻', 'violin'],
      ['🎼', 'musical_score'], ['🎾', 'tennis_racquet_and_ball'], ['🏀', 'basketball_and_hoop'], ['🏄', 'surfer'],
      ['🏅', 'sports_medal'], ['🏆', 'trophy'], ['🏊', 'swimmer'], ['🏌', 'golfer'],
      ['🏍', 'racing_motorcycle'], ['🏎', 'racing_car'], ['🏐', 'volleyball'], ['🏑', 'field_hockey_stick_and_ball'],
      ['🏒', 'ice_hockey_stick_and_puck'], ['🏓', 'table_tennis_paddle_and_ball'], ['🏸', 'badminton_racquet_and_shuttlecock'], ['💳', 'credit_card'],
      ['📇', 'card_index'], ['📽', 'film_projector'], ['🖊', 'lower_left_ballpoint_pen'], ['🖲', 'trackball'],
      ['🗂', 'card_index_dividers'], ['🗴', 'ballot_script_x'], ['🗶', 'ballot_bold_script_x'], ['🚲', 'bicycle'],
      ['🚳', 'no_bicycles'], ['🚴', 'bicyclist'], ['🚵', 'mountain_bicyclist'], ['🛢', 'oil_drum'],
      ['🛲', 'diesel_locomotive'], ['🛷', 'sled'], ['🛼', 'roller_skate'], ['🤹', 'juggling'],
      ['🤼', 'wrestlers'], ['🥁', 'drum_with_drumsticks'], ['🥇', 'first_place_medal'], ['🥈', 'second_place_medal'],
      ['🥉', 'third_place_medal'], ['🥋', 'martial_arts_uniform'], ['🥌', 'curling_stone'], ['🥍', 'lacrosse_stick_and_ball'],
      ['🥎', 'softball'], ['🧧', 'red_gift_envelope'], ['🧶', 'ball_of_yarn'], ['🪀', 'yo_yo'],
      ['🪁', 'kite'], ['🪃', 'boomerang'], ['🪕', 'banjo'], ['🪗', 'accordion'],
      ['🪘', 'long_drum'], ['🪧', 'placard'], ['🪩', 'mirror_ball'], ['⚽', 'soccer_ball'],
      ['⚾', 'baseball'],
    ],
  },
  {
    id: 'travel',
    label: 'Travel & places',
    items: [
      ['🌉', 'bridge_at_night'], ['🎎', 'japanese_dolls'], ['🎏', 'carp_streamer'], ['🎒', 'school_satchel'],
      ['🎡', 'ferris_wheel'], ['🎢', 'roller_coaster'], ['🏕', 'camping'], ['🏖', 'beach_with_umbrella'],
      ['🏗', 'building_construction'], ['🏘', 'house_buildings'], ['🏚', 'derelict_house_building'], ['🏛', 'classical_building'],
      ['🏜', 'desert'], ['🏝', 'desert_island'], ['🏟', 'stadium'], ['🏠', 'house_building'],
      ['🏡', 'house_with_garden'], ['🏢', 'office_building'], ['🏣', 'japanese_post_office'], ['🏤', 'european_post_office'],
      ['🏥', 'hospital'], ['🏦', 'bank'], ['🏨', 'hotel'], ['🏩', 'love_hotel'],
      ['🏪', 'convenience_store'], ['🏫', 'school'], ['🏬', 'department_store'], ['🏭', 'factory'],
      ['🏯', 'japanese_castle'], ['🏰', 'european_castle'], ['💈', 'barber_pole'], ['💒', 'wedding'],
      ['💴', 'banknote_with_yen_sign'], ['💵', 'banknote_with_dollar_sign'], ['💶', 'banknote_with_euro_sign'], ['💷', 'banknote_with_pound_sign'],
      ['🔰', 'japanese_symbol_for_beginner'], ['🕋', 'kaaba'], ['🕌', 'mosque'], ['🕍', 'synagogue'],
      ['🖋', 'lower_left_fountain_pen'], ['🖭', 'tape_cartridge'], ['🗺', 'world_map'], ['🗼', 'tokyo_tower'],
      ['🗽', 'statue_of_liberty'], ['🚀', 'rocket'], ['🚁', 'helicopter'], ['🚃', 'railway_car'],
      ['🚇', 'metro'], ['🚉', 'station'], ['🚌', 'bus'], ['🚍', 'oncoming_bus'],
      ['🚎', 'trolleybus'], ['🚏', 'bus_stop'], ['🚐', 'minibus'], ['🚑', 'ambulance'],
      ['🚕', 'taxi'], ['🚖', 'oncoming_taxi'], ['🚚', 'delivery_truck'], ['🚜', 'tractor'],
      ['🚞', 'mountain_railway'], ['🚟', 'suspension_railway'], ['🚠', 'mountain_cableway'], ['🚢', 'ship'],
      ['🚣', 'rowboat'], ['🚤', 'speedboat'], ['🚥', 'horizontal_traffic_light'], ['🚦', 'vertical_traffic_light'],
      ['🛂', 'passport_control'], ['🛅', 'left_luggage'], ['🛐', 'place_of_worship'], ['🛕', 'hindu_temple'],
      ['🛖', 'hut'], ['🛤', 'railway_track'], ['🛥', 'motor_boat'], ['🛦', 'up_pointing_military_airplane'],
      ['🛧', 'up_pointing_airplane'], ['🛨', 'up_pointing_small_airplane'], ['🛩', 'small_airplane'], ['🛪', 'northeast_pointing_airplane'],
      ['🛫', 'airplane_departure'], ['🛬', 'airplane_arriving'], ['🛰', 'satellite'], ['🛳', 'passenger_ship'],
      ['🛴', 'scooter'], ['🛵', 'motor_scooter'], ['🛻', 'pickup_truck'], ['🧭', 'compass'],
      ['🧳', 'luggage'], ['🪂', 'parachute'], ['🪚', 'carpentry_saw'], ['🪨', 'rock'],
      ['🪵', 'wood'], ['⛵', 'sailboat'], ['⛽', 'fuel_pump'], ['✈️', 'airplane'],
    ],
  },
  {
    id: 'objects',
    label: 'Objects & symbols',
    items: [
      ['🌀', 'cyclone'], ['🌂', 'closed_umbrella'], ['🌡', 'thermometer'], ['🌺', 'hibiscus'],
      ['🍆', 'aubergine'], ['🍝', 'spaghetti'], ['🍡', 'dango'], ['🍢', 'oden'],
      ['🍳', 'cooking'], ['🍹', 'tropical_drink'], ['🎁', 'wrapped_present'], ['🎅', 'father_christmas'],
      ['🎌', 'crossed_flags'], ['🎍', 'pine_decoration'], ['🎚', 'level_slider'], ['🎛', 'control_knobs'],
      ['🎥', 'movie_camera'], ['🎦', 'cinema'], ['🎯', 'direct_hit'], ['🎰', 'slot_machine'],
      ['🎱', 'billiards'], ['🏁', 'chequered_flag'], ['🏃', 'runner'], ['🏋', 'weight_lifter'],
      ['🏞', 'national_park'], ['🏳', 'waving_white_flag'], ['🏴', 'waving_black_flag'], ['🏷', 'label'],
      ['🏹', 'bow_and_arrow'], ['🏺', 'amphora'], ['🐀', 'rat'], ['🐓', 'rooster'],
      ['🐿', 'chipmunk'], ['👔', 'necktie'], ['👝', 'pouch'], ['👰', 'bride_with_veil'],
      ['👿', 'imp'], ['💊', 'pill'], ['💌', 'love_letter'], ['💎', 'gem_stone'],
      ['💠', 'diamond_shape_with_a_dot_inside'], ['💡', 'electric_light_bulb'], ['💢', 'anger_symbol'], ['💣', 'bomb'],
      ['💥', 'collision_symbol'], ['💦', 'splashing_sweat_symbol'], ['💨', 'dash_symbol'], ['💪', 'flexed_biceps'],
      ['💫', 'dizzy_symbol'], ['💯', 'hundred_points_symbol'], ['💰', 'money_bag'], ['💱', 'currency_exchange'],
      ['💲', 'heavy_dollar_sign'], ['💹', 'chart_with_upwards_trend_and_yen_sign'], ['💺', 'seat'], ['💼', 'briefcase'],
      ['💽', 'minidisc'], ['💾', 'floppy_disk'], ['💿', 'optical_disc'], ['📀', 'dvd'],
      ['📃', 'page_with_curl'], ['📄', 'page_facing_up'], ['📅', 'calendar'], ['📈', 'chart_with_upwards_trend'],
      ['📉', 'chart_with_downwards_trend'], ['📊', 'bar_chart'], ['📌', 'pushpin'], ['📍', 'round_pushpin'],
      ['📎', 'paperclip'], ['📏', 'straight_ruler'], ['📐', 'triangular_ruler'], ['📑', 'bookmark_tabs'],
      ['📒', 'ledger'], ['📓', 'notebook'], ['📔', 'notebook_with_decorative_cover'], ['📕', 'closed_book'],
      ['📖', 'open_book'], ['📗', 'green_book'], ['📘', 'blue_book'], ['📙', 'orange_book'],
      ['📚', 'books'], ['📛', 'name_badge'], ['📜', 'scroll'], ['📝', 'memo'],
      ['📞', 'telephone_receiver'], ['📟', 'pager'], ['📠', 'fax_machine'], ['📦', 'package'],
      ['📧', 'e_mail_symbol'], ['📨', 'incoming_envelope'], ['📩', 'envelope_with_downwards_arrow_above'], ['📯', 'postal_horn'],
      ['📰', 'newspaper'], ['📱', 'mobile_phone'], ['📲', 'mobile_phone_with_rightwards_arrow_at_left'], ['📳', 'vibration_mode'],
      ['📴', 'mobile_phone_off'], ['📵', 'no_mobile_phones'], ['📷', 'camera'], ['📸', 'camera_with_flash'],
      ['📹', 'video_camera'], ['📺', 'television'], ['📻', 'radio'], ['📼', 'videocassette'],
      ['📾', 'portable_stereo'], ['🔀', 'twisted_rightwards_arrows'], ['🔁', 'clockwise_rightwards_and_leftwards_open_circle_arrows'], ['🔂', 'clockwise_rightwards_and_leftwards_open_circle_arrows_with_circled_one_overlay'],
      ['🔃', 'clockwise_downwards_and_upwards_open_circle_arrows'], ['🔅', 'low_brightness_symbol'], ['🔆', 'high_brightness_symbol'], ['🔈', 'speaker'],
      ['🔌', 'electric_plug'], ['🔍', 'left_pointing_magnifying_glass'], ['🔎', 'right_pointing_magnifying_glass'], ['🔏', 'lock_with_ink_pen'],
      ['🔐', 'closed_lock_with_key'], ['🔑', 'key'], ['🔒', 'lock'], ['🔓', 'open_lock'],
      ['🔔', 'bell'], ['🔖', 'bookmark'], ['🔗', 'link_symbol'], ['🔘', 'radio_button'],
      ['🔙', 'back_with_leftwards_arrow_above'], ['🔚', 'end_with_leftwards_arrow_above'], ['🔛', 'on_with_exclamation_mark_with_left_right_arrow_above'], ['🔜', 'soon_with_rightwards_arrow_above'],
      ['🔝', 'top_with_upwards_arrow_above'], ['🔞', 'no_one_under_eighteen_symbol'], ['🔡', 'input_symbol_for_latin_small_letters'], ['🔢', 'input_symbol_for_numbers'],
      ['🔣', 'input_symbol_for_symbols'], ['🔤', 'input_symbol_for_latin_letters'], ['🔦', 'electric_torch'], ['🔧', 'wrench'],
      ['🔨', 'hammer'], ['🔩', 'nut_and_bolt'], ['🔪', 'hocho'], ['🔫', 'pistol'],
      ['🔬', 'microscope'], ['🔭', 'telescope'], ['🔱', 'trident_emblem'], ['🔲', 'black_square_button'],
      ['🔳', 'white_square_button'], ['🔴', 'large_red_circle'], ['🔵', 'large_blue_circle'], ['🔶', 'large_orange_diamond'],
      ['🔷', 'large_blue_diamond'], ['🔸', 'small_orange_diamond'], ['🔹', 'small_blue_diamond'], ['🔺', 'up_pointing_red_triangle'],
      ['🔻', 'down_pointing_red_triangle'], ['🔼', 'up_pointing_small_red_triangle'], ['🔽', 'down_pointing_small_red_triangle'], ['🔾', 'lower_right_shadowed_white_circle'],
      ['🔿', 'upper_right_shadowed_white_circle'], ['🕀', 'circled_cross_pommee'], ['🕁', 'cross_pommee_with_half_circle_below'], ['🕂', 'cross_pommee'],
      ['🕃', 'notched_left_semicircle_with_three_dots'], ['🕄', 'notched_right_semicircle_with_three_dots'], ['🕅', 'symbol_for_marks_chapter'], ['🕆', 'white_latin_cross'],
      ['🕇', 'heavy_latin_cross'], ['🕈', 'celtic_cross'], ['🕉', 'om_symbol'], ['🕊', 'dove_of_peace'],
      ['🕎', 'menorah_with_nine_branches'], ['🕨', 'right_speaker'], ['🕫', 'bullhorn'], ['🕮', 'book'],
      ['🕲', 'no_piracy'], ['🕵', 'sleuth_or_spy'], ['🕹', 'joystick'], ['🕼', 'telephone_receiver_with_page'],
      ['🕾', 'white_touchtone_telephone'], ['🕿', 'black_touchtone_telephone'], ['🖀', 'telephone_on_top_of_modem'], ['🖂', 'back_of_envelope'],
      ['🖃', 'stamped_envelope'], ['🖄', 'envelope_with_lightning'], ['🖆', 'pen_over_stamped_envelope'], ['🖈', 'black_pushpin'],
      ['🖉', 'lower_left_pencil'], ['🖌', 'lower_left_paintbrush'], ['🖍', 'lower_left_crayon'], ['🖘', 'sideways_white_left_pointing_index'],
      ['🖙', 'sideways_white_right_pointing_index'], ['🖚', 'sideways_black_left_pointing_index'], ['🖛', 'sideways_black_right_pointing_index'], ['🖞', 'sideways_white_up_pointing_index'],
      ['🖟', 'sideways_white_down_pointing_index'], ['🖠', 'sideways_black_up_pointing_index'], ['🖡', 'sideways_black_down_pointing_index'], ['🖥', 'desktop_computer'],
      ['🖧', 'three_networked_computers'], ['🖨', 'printer'], ['🖩', 'pocket_calculator'], ['🖴', 'hard_disk'],
      ['🖵', 'screen'], ['🖶', 'printer_icon'], ['🖷', 'fax_icon'], ['🖸', 'optical_disc_icon'],
      ['🖹', 'document_with_text'], ['🖺', 'document_with_text_and_picture'], ['🖻', 'document_with_picture'], ['🗄', 'file_cabinet'],
      ['🗅', 'empty_note'], ['🗆', 'empty_note_page'], ['🗇', 'empty_note_pad'], ['🗈', 'note'],
      ['🗉', 'note_page'], ['🗊', 'note_pad'], ['🗋', 'empty_document'], ['🗌', 'empty_page'],
      ['🗍', 'empty_pages'], ['🗎', 'document'], ['🗏', 'page'], ['🗐', 'pages'],
      ['🗑', 'wastebasket'], ['🗒', 'spiral_note_pad'], ['🗓', 'spiral_calendar_pad'], ['🗕', 'minimize'],
      ['🗖', 'maximize'], ['🗗', 'overlap'], ['🗘', 'clockwise_right_and_left_semicircle_arrows'], ['🗚', 'increase_font_size_symbol'],
      ['🗛', 'decrease_font_size_symbol'], ['🗜', 'compression'], ['🗝', 'old_key'], ['🗞', 'rolled_up_newspaper'],
      ['🗟', 'page_with_circled_text'], ['🗠', 'stock_chart'], ['🗤', 'three_rays_above'], ['🗥', 'three_rays_below'],
      ['🗦', 'three_rays_left'], ['🗧', 'three_rays_right'], ['🗬', 'left_thought_bubble'], ['🗭', 'right_thought_bubble'],
      ['🗮', 'left_anger_bubble'], ['🗯', 'right_anger_bubble'], ['🗰', 'mood_bubble'], ['🗱', 'lightning_mood_bubble'],
      ['🗲', 'lightning_mood'], ['🗸', 'light_check_mark'], ['🗻', 'mount_fuji'], ['🗾', 'silhouette_of_japan'],
      ['🗿', 'moyai'], ['🚂', 'steam_locomotive'], ['🚈', 'light_rail'], ['🚗', 'automobile'],
      ['🚘', 'oncoming_automobile'], ['🚙', 'recreational_vehicle'], ['🚛', 'articulated_lorry'], ['🚝', 'monorail'],
      ['🚧', 'construction_sign'], ['🚩', 'triangular_flag_on_post'], ['🚪', 'door'], ['🚫', 'no_entry_sign'],
      ['🚬', 'smoking_symbol'], ['🚭', 'no_smoking_symbol'], ['🚮', 'put_litter_in_its_place_symbol'], ['🚯', 'do_not_litter_symbol'],
      ['🚶', 'pedestrian'], ['🚷', 'no_pedestrians'], ['🚸', 'children_crossing'], ['🚹', 'mens_symbol'],
      ['🚺', 'womens_symbol'], ['🚻', 'restroom'], ['🚽', 'toilet'], ['🚿', 'shower'],
      ['🛃', 'customs'], ['🛄', 'baggage_claim'], ['🛇', 'prohibited_sign'], ['🛈', 'circled_information_source'],
      ['🛋', 'couch_and_lamp'], ['🛍', 'shopping_bags'], ['🛎', 'bellhop_bell'], ['🛏', 'bed'],
      ['🛑', 'octagonal_sign'], ['🛒', 'shopping_trolley'], ['🛓', 'stupa'], ['🛔', 'pagoda'],
      ['🛗', 'elevator'], ['🛜', 'wireless'], ['🛝', 'playground_slide'], ['🛞', 'wheel'],
      ['🛠', 'hammer_and_wrench'], ['🛡', 'shield'], ['🛣', 'motorway'], ['🛺', 'auto_rickshaw'],
      ['🤀', 'circled_cross_formee_with_four_dots'], ['🤁', 'circled_cross_formee_with_two_dots'], ['🤂', 'circled_cross_formee'], ['🤃', 'left_half_circle_with_four_dots'],
      ['🤄', 'left_half_circle_with_three_dots'], ['🤅', 'left_half_circle_with_two_dots'], ['🤆', 'left_half_circle_with_dot'], ['🤇', 'left_half_circle'],
      ['🤈', 'downward_facing_hook'], ['🤉', 'downward_facing_notched_hook'], ['🤊', 'downward_facing_hook_with_dot'], ['🤋', 'downward_facing_notched_hook_with_dot'],
      ['🤘', 'sign_of_the_horns'], ['🤣', 'rolling_on_the_floor_laughing'], ['🤱', 'breast_feeding'], ['🤶', 'mother_christmas'],
      ['🤷', 'shrug'], ['🤺', 'fencer'], ['🤻', 'modern_pentathlon'], ['🤿', 'diving_mask'],
      ['🥅', 'goal_net'], ['🥆', 'rifle'], ['🥽', 'goggles'], ['🦃', 'turkey'],
      ['🦔', 'hedgehog'], ['🦖', 't_rex'], ['🦘', 'kangaroo'], ['🦙', 'llama'],
      ['🦝', 'raccoon'], ['🦬', 'bison'], ['🦲', 'emoji_component_bald'], ['🦺', 'safety_vest'],
      ['🧊', 'ice_cube'], ['🧌', 'troll'], ['🧒', 'child'], ['🧪', 'test_tube'],
      ['🧫', 'petri_dish'], ['🧬', 'dna_double_helix'], ['🧮', 'abacus'], ['🧱', 'brick'],
      ['🧲', 'magnet'], ['🧵', 'spool_of_thread'], ['🧷', 'safety_pin'], ['🧹', 'broom'],
      ['🧺', 'basket'], ['🧻', 'roll_of_paper'], ['🧼', 'bar_of_soap'], ['🧽', 'sponge'],
      ['🧾', 'receipt'], ['🧿', 'nazar_amulet'], ['🩲', 'briefs'], ['🩳', 'shorts'],
      ['🩸', 'drop_of_blood'], ['🩹', 'adhesive_bandage'], ['🩺', 'stethoscope'], ['🩻', 'x_ray'],
      ['🩼', 'crutch'], ['🪄', 'magic_wand'], ['🪅', 'pinata'], ['🪇', 'maracas'],
      ['🪈', 'flute'], ['🪉', 'harp'], ['🪏', 'shovel'], ['🪒', 'razor'],
      ['🪓', 'axe'], ['🪔', 'diya_lamp'], ['🪖', 'military_helmet'], ['🪙', 'coin'],
      ['🪛', 'screwdriver'], ['🪜', 'ladder'], ['🪝', 'hook'], ['🪞', 'mirror'],
      ['🪢', 'knot'], ['🪣', 'bucket'], ['🪦', 'headstone'], ['🪬', 'hamsa'],
      ['🪻', 'hyacinth'], ['🪿', 'goose'], ['🫎', 'moose'], ['🫏', 'donkey'],
      ['🫐', 'blueberries'], ['🫒', 'olive'], ['🫚', 'ginger_root'], ['🫛', 'pea_pod'],
      ['🫟', 'splatter'], ['🫦', 'biting_lip'], ['🫧', 'bubbles'], ['🫵', 'index_pointing_at_the_viewer'],
      ['✅', 'check_mark'], ['❌', 'cross_mark'], ['❗', 'exclamation'], ['❓', 'question'],
      ['⚡', 'high_voltage'], ['✨', 'sparkles'], ['⚕️', 'medical_symbol'], ['♻️', 'recycling'],
      ['⚠️', 'warning'], ['✔️', 'check'], ['➕', 'plus'], ['➖', 'minus'],
      ['➗', 'divide'], ['➡️', 'right_arrow'], ['⬅️', 'left_arrow'], ['⬆️', 'up_arrow'],
      ['⬇️', 'down_arrow'], ['⌛', 'hourglass'], ['☎️', 'telephone'], ['✉️', 'envelope'],
      ['✏️', 'pencil'], ['✂️', 'scissors'], ['⚒️', 'hammer_and_pick'], ['⚜️', 'fleur_de_lis'],
      ['♠️', 'spades'], ['♦️', 'diamonds'], ['♣️', 'clubs'], ['♊', 'gemini'],
      ['▶️', 'play'], ['⏯️', 'play_pause'], ['⏸️', 'pause'], ['⏹️', 'stop'],
      ['⁉️', 'exclamation_question'], ['‼️', 'double_exclamation'], ['〰️', 'wavy_dash'], ['™', 'trade_mark'],
      ['©️', 'copyright'], ['®️', 'registered'], ['⛔', 'no_entry'], ['☢️', 'radioactive'],
      ['☣️', 'biohazard'], ['☮️', 'peace'], ['✳️', 'eight_spoked_asterisk'], ['❇️', 'sparkle'],
      ['㊗️', 'congratulations'], ['㊙️', 'secret'], ['⌚', 'watch'],
    ],
  },
];

/**
 * Name to character, for turning a typed :shortcode: into an emoji.
 *
 * Custom emoji are looked up FIRST and are not in here -- a server that
 * names one :pizza: means that picture, on its own server, and surprising
 * somebody with the standard one would be worse than the collision.
 */
export const EMOJI_BY_NAME = new Map(
  // [char, name] pairs, reversed: the entries are ordered for the grid,
  // which draws characters, and this is the lookup that goes the other way.
  EMOJI_SECTIONS.flatMap((section) => section.items.map(([ch, name]) => [name, ch])),
);

/**
 * The names people actually type.
 *
 * Unicode's own name for the thumbs up is THUMBS UP SIGN, so the generated
 * shortcode is :thumbs_up_sign:, which nobody has ever typed. These are the
 * short ones everybody learned somewhere else, mapped by hand -- the only
 * part of this file that is not generated, and the only part that needs
 * touching when a new one becomes common.
 *
 * Search still matches on the generated names, so typing "thumbs" finds it
 * without any of this.
 */
export const EMOJI_ALIASES = new Map([
  ['thumbsup', '\u{1F44D}'], ['+1', '\u{1F44D}'], ['thumbsdown', '\u{1F44E}'],
  ['-1', '\u{1F44E}'], ['joy', '\u{1F602}'], ['rofl', '\u{1F923}'],
  ['sob', '\u{1F62D}'], ['cry', '\u{1F622}'], ['smile', '\u{1F604}'],
  ['grin', '\u{1F601}'], ['wink', '\u{1F609}'], ['heart', '\u2764\ufe0f'],
  ['fire', '\u{1F525}'], ['100', '\u{1F4AF}'], ['tada', '\u{1F389}'],
  ['party', '\u{1F389}'], ['eyes', '\u{1F440}'], ['ok', '\u{1F44C}'],
  ['pray', '\u{1F64F}'], ['clap', '\u{1F44F}'], ['wave', '\u{1F44B}'],
  ['rocket', '\u{1F680}'], ['skull', '\u{1F480}'], ['poop', '\u{1F4A9}'],
  ['shrug', '\u{1F937}'], ['facepalm', '\u{1F926}'], ['think', '\u{1F914}'],
  ['thinking', '\u{1F914}'], ['sunglasses', '\u{1F60E}'], ['cool', '\u{1F60E}'],
  ['sweat', '\u{1F605}'], ['pensive', '\u{1F614}'], ['rage', '\u{1F621}'],
  ['angry', '\u{1F620}'], ['sleepy', '\u{1F634}'], ['star', '\u2b50'],
  ['check', '\u2705'], ['x', '\u274C'], ['warning', '\u26A0\ufe0f'],
  ['brain', '\u{1F9E0}'], ['salt', '\u{1F9C2}'], ['beer', '\u{1F37A}'],
  ['pizza', '\u{1F355}'], ['cat', '\u{1F431}'], ['dog', '\u{1F436}'],
  ['frog', '\u{1F438}'], ['snake', '\u{1F40D}'], ['bug', '\u{1F41B}'],
  ['moon', '\u{1F319}'], ['sun', '\u2600\ufe0f'], ['zzz', '\u{1F4A4}'],
]);

/** A typed :name:, resolved against the aliases and then the full set. */
export const emojiByShortcode = (name) =>
  EMOJI_ALIASES.get(name) ?? EMOJI_BY_NAME.get(name) ?? null;

/** Everything, flat, for search. */
export const ALL_EMOJI = EMOJI_SECTIONS.flatMap((s) => s.items);
